require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe NutritionsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Nutrition. As you add validations to Nutrition, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NutritionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all nutritions as @nutritions" do
      nutrition = Nutrition.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:nutritions)).to eq([nutrition])
    end
  end

  describe "GET #show" do
    it "assigns the requested nutrition as @nutrition" do
      nutrition = Nutrition.create! valid_attributes
      get :show, {:id => nutrition.to_param}, valid_session
      expect(assigns(:nutrition)).to eq(nutrition)
    end
  end

  describe "GET #new" do
    it "assigns a new nutrition as @nutrition" do
      get :new, {}, valid_session
      expect(assigns(:nutrition)).to be_a_new(Nutrition)
    end
  end

  describe "GET #edit" do
    it "assigns the requested nutrition as @nutrition" do
      nutrition = Nutrition.create! valid_attributes
      get :edit, {:id => nutrition.to_param}, valid_session
      expect(assigns(:nutrition)).to eq(nutrition)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Nutrition" do
        expect {
          post :create, {:nutrition => valid_attributes}, valid_session
        }.to change(Nutrition, :count).by(1)
      end

      it "assigns a newly created nutrition as @nutrition" do
        post :create, {:nutrition => valid_attributes}, valid_session
        expect(assigns(:nutrition)).to be_a(Nutrition)
        expect(assigns(:nutrition)).to be_persisted
      end

      it "redirects to the created nutrition" do
        post :create, {:nutrition => valid_attributes}, valid_session
        expect(response).to redirect_to(Nutrition.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved nutrition as @nutrition" do
        post :create, {:nutrition => invalid_attributes}, valid_session
        expect(assigns(:nutrition)).to be_a_new(Nutrition)
      end

      it "re-renders the 'new' template" do
        post :create, {:nutrition => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested nutrition" do
        nutrition = Nutrition.create! valid_attributes
        put :update, {:id => nutrition.to_param, :nutrition => new_attributes}, valid_session
        nutrition.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested nutrition as @nutrition" do
        nutrition = Nutrition.create! valid_attributes
        put :update, {:id => nutrition.to_param, :nutrition => valid_attributes}, valid_session
        expect(assigns(:nutrition)).to eq(nutrition)
      end

      it "redirects to the nutrition" do
        nutrition = Nutrition.create! valid_attributes
        put :update, {:id => nutrition.to_param, :nutrition => valid_attributes}, valid_session
        expect(response).to redirect_to(nutrition)
      end
    end

    context "with invalid params" do
      it "assigns the nutrition as @nutrition" do
        nutrition = Nutrition.create! valid_attributes
        put :update, {:id => nutrition.to_param, :nutrition => invalid_attributes}, valid_session
        expect(assigns(:nutrition)).to eq(nutrition)
      end

      it "re-renders the 'edit' template" do
        nutrition = Nutrition.create! valid_attributes
        put :update, {:id => nutrition.to_param, :nutrition => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested nutrition" do
      nutrition = Nutrition.create! valid_attributes
      expect {
        delete :destroy, {:id => nutrition.to_param}, valid_session
      }.to change(Nutrition, :count).by(-1)
    end

    it "redirects to the nutritions list" do
      nutrition = Nutrition.create! valid_attributes
      delete :destroy, {:id => nutrition.to_param}, valid_session
      expect(response).to redirect_to(nutritions_url)
    end
  end

end
